.github/workflows/ci.yml, .github/workflows/pr.yml
With respect to the issue, 
https://github.com/EXXETA/trufos/issues/167
Updated the GitHub Actions workflows to prevent pipelines from running for draft pull requests by adding a condition to check the draft status. This optimization ensures that workflows are triggered only for pull requests that are ready for review, reducing unnecessary resource usage and saving worker minutes.
=> #167 - skip CI if PR is draft

src/renderer/components/mainWindow/MainTopBar.tsx
Fixes https://github.com/EXXETA/trufos/issues/161
This PR adds hotkey support (Ctrl+S for Windows/Linux and Cmd+S for Mac) to quickly save the currently opened request in the MainTopBar.
=> #161 - Add Hotkey support(ctrl + s/cmd + s) to save opened requests.

.github/pull_request_template.md, CONTRIBUTING.md, README.md
Delete  "Commit messages, branch names, code formatting adheres to our Contributing Guidelines" from pr template
close #179 
If relevant, mention your manual testing here. If possible, include screenshots.
](https://github.com/EXXETA/rufus/blob/main/CONTRIBUTING.md)
=> #179 - optimize pr template

src/main/environment/service/environment-service.test.ts, src/main/environment/service/environment-service.ts, src/main/event/main-event-service.ts, src/main/main.ts, src/main/persistence/service/default-collection.ts, src/main/persistence/service/info-files/latest.ts, src/main/persistence/service/persistence-service.test.ts, src/main/persistence/service/persistence-service.ts, src/main/persistence/service/settings-service.test.ts, src/main/persistence/service/settings-service.ts, src/renderer/services/event/renderer-event-service.ts, src/shim/event-service.ts
- Support creating new and opening or switching existing collections
- Fix a bug where the `fromRequestInfoFile()` does load draft requests but only the persisted
Only backend, automated tests are written.
=> feat(#206): Support switching and creating Collections

src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx
This PR fixes the naming model placeholder to differentiate between naming a folder or request.
close #288 
- Added a content type and the 'trufus' object type as a variable to the placeholder value using template literals.
- Added a nullish operator to check whether the content type is null or not. If it is null that means it's a rename process and the variable will be the 'trufus' object type which is the collection type that was created (Folder/ Request ). If It's not null that means we are creating a new (Folder/request).
=> #288 - bug/ fix the naming model component placeholder 

package.json, src/main/__mocks__/electron/app.ts, src/main/__mocks__/electron/index.ts, src/main/__mocks__/electron/ipc-main.ts, src/main/__mocks__/index.ts, src/main/environment/service/environment-service.ts, src/main/event/main-event-service.ts, src/main/import/service/import-service.ts, src/main/import/service/postman-importer.ts, src/main/logging/logger.test.ts, src/main/logging/logger.ts, src/main/main.ts, src/main/network/service/http-service.ts, src/main/persistence/service/info-files/migrators.ts, src/main/persistence/service/persistence-service.ts, src/main/persistence/service/settings-service.ts, src/renderer/index.tsx, src/renderer/logging/console.ts, src/shim/logger.ts, yarn.lock
Use winston to log
- `console` logs from renderer
- `logger` logs from main
The renderer `console` log methods are overwritten to redirect the log message to main, where they are written to FS. The `logger` is a new global variable, available in main. `console` should not be used in main anymore.
FS logger logic:
- max 10 files
- tailable (current file is always `trufos.log`)
- max 10MiB per file
```
2025-03-16 19:16:31 [MAIN] [INFO]: Loading collection at
2025-03-16 19:16:31 [MAIN] [INFO]: Migrated from version 1.0.1 to 1.1.0
2025-03-16 19:16:31.383 Electron[54635:9276667] +[IMKClient subclass]: chose IMKClient_Modern
2025-03-16 19:16:31.383 Electron[54635:9276667] +[IMKInputSession subclass]: chose IMKInputSession_Modern
2025-03-16 19:16:32 [RENDERER] [INFO]: Download the React DevTools …
```
=> feat(77): Logging Framework

src/main/logging/logger.test.ts, src/main/logging/logger.ts
- Printing any extra arguments of logger
- Printing error stacktraces (if it's last element in log statement)
- Set FS log level to warning
```
2025-04-04T20:12:32.114Z [RENDERER] [INFO]: initialize {
id: '7c966850-a7a1-4621-90b4-b798a76ccfeb',
title: 'Default Collection',
... and so on
```
=> fix(337): Logger not printing extra Arguments

examples/collection/collection.json, examples/collection/echo/request-body.txt, examples/collection/echo/request.json, src/main/environment/service/environment-service.ts, src/main/event/main-event-service.ts, src/main/persistence/service/persistence-service.test.ts, src/main/persistence/service/persistence-service.ts, src/renderer/components/sidebar/SidebarHeaderBar.tsx, src/renderer/services/event/renderer-event-service.ts, src/renderer/state/collectionStore.ts, src/renderer/state/interface/CollectionStateActions.ts, src/renderer/view/Menubar.tsx, src/shim/event-service.ts
- Add `showOpenDialog()` event method that allows showing a native dialog to open a file or directory
- Add a button to open an existing collection (`collection.json` file)
- Add a button to create a new collection in a selected directory (must be empty)
- Add `changeCollection()` action to collection store
- Add `examples/collection` directory to repository
- When loading of current collection fails on boot, default collection is loaded instead
- Create `.gitignore` when creating new collection to prevent committing draft requests
**Open existing Collection:**
https://github.com/user-attachments/assets/53eb604f-c10a-4289-a767-50f73e2b9c74
=> feat(303): Temporary Buttons for opening Collections

src/main/environment/service/environment-service.test.ts, src/main/environment/service/environment-service.ts, src/main/event/main-event-service.ts, src/main/persistence/service/persistence-service.test.ts, src/main/persistence/service/persistence-service.ts, src/main/persistence/service/settings-service.ts, src/main/util/object-util.ts, src/renderer/components/sidebar/CollectionDropdown.tsx, src/renderer/components/sidebar/SidebarHeaderBar.tsx, src/renderer/services/event/renderer-event-service.ts, src/shim/event-service.ts, src/shim/objects/collection.ts
- Support loading a list of all opened collections in backend
- Merge "Open Collection" and "New Collection" button to dropdown
- Support switching collections in dropdown
=> feat(304): Collection Selection Dropdown

src/main/persistence/service/persistence-service.test.ts, src/main/persistence/service/persistence-service.ts
This PR fixes the issue outlined in #307 where it was possible for one trufos object to overwrite another trufos object if they have a similar title, causing the resolved dir name to be the same.
With the change from this PR, when assigning a new dir path for an object, we check if the dir path is already taken and append a number to the dir name until a name is found that is not taken.
I tested these changes manually by creating a couple of trufos requests in the UI and checking which directories are created. Additionally I changed some data inside the requests to see if the correct files are overwritten when saving the requests.
I also added a unit test that tests this scenario.
=> #307 - Resolve dir path naming conflicts

src/renderer/components/mainWindow/bodyTabs/InputTabs/tabs/HeaderTab.tsx
- Fixes #336
- I modified the code to set the draft flag within the event handlers in `HeaderTabs.tsx`. However, if preferred, I can update the corresponding header functions (`addHeader`, `deleteHeader` etc.) in `collectionStore.ts` to set the draft flag directly within those functions. Let me know if you'd like me to modify the PR accordingly.
I tested the fix manually as can be seen in the video below.
https://github.com/user-attachments/assets/59c8edab-41ba-499b-ab8f-4d6283060b51
=> fix(336): Set draft state when modifying request headers

src/renderer/components/mainWindow/MainBody.tsx, src/renderer/components/mainWindow/bodyTabs/OutputTabs.tsx, src/renderer/view/RequestWindow.tsx
- Closes #205
- For screen sizes `>= 1280px`, the two main body elements are displayed side by side, each occupying equal width
- For screen sizes `< 1280px`, the elements stack vertically, each taking equal height
- Simplified and unified `className` syntax in modified files to use the standard `className="..."` format
The feature has been manually tested as can be seen in the video.
https://github.com/user-attachments/assets/ecbef50e-c595-40a1-b868-3f75899adfef
=> feat(205): Responsive layout for main body items based on screen size

src/main/preload.ts, src/renderer/components/mainWindow/MainBody.tsx, src/renderer/components/mainWindow/bodyTabs/InputTabs/tabs/BodyTab.tsx, src/renderer/components/mainWindow/bodyTabs/InputTabs/tabs/BodyTabFileInput.tsx, src/renderer/components/mainWindow/bodyTabs/InputTabs/tabs/BodyTabTextInput.tsx, src/renderer/components/mainWindow/bodyTabs/OutputTabs.tsx, src/renderer/view/RequestWindow.tsx, src/shim/objects/request.ts
- Closes #65
- Introduces a drag-and-drop zone for request bodies with a file:
- The drop zone highlights with a border when a file is dragged over it
- Users can also click the zone to manually select a file from the file system
- Separates the text and file input components for the request body, improving clarity and modularity
- Replaces some `flex` layouts with `grid` to resolve overflow issues caused by truncated text and to enhance responsive behavior
- Improves styling of the Monaco Editor by setting its position to `absolute`, ensuring it respects the height and width of its parent container
Since no design reference was provided in the issue for the drag-and-drop zone, I implemented a design shown in the video below. I'm happy to update the styling if there's a preferred …
=> feat(65) - Add drag and drop zone for a request body file

src/renderer/components/mainWindow/MainTopBar.tsx
#389 - URL input field keeps red error border after switching to a valid request
This PR addresses issue #389 by ensuring that the error border on the URL input field is cleared when a valid request is detected. Previously, the error state persisted even after a valid URL and method were selected.
- Added a `useEffect` hook to monitor changes in the `request` object.
- Clears the error state (`setHasError(false)`) when both `request.url` and `request.method` are valid.
Tested the fix based off the reproduce steps in the bug issue post:
- Removed content from input bar (invalid URL) to reproduce error state.
- Switched to a valid URL and confirming that the error border disappears.
=> fix(389): Fix persistent error border on URL input when switching to valid request

src/renderer/state/collectionStore.ts
- Prevent collapsing Folders when modifying Collection Items by keeping previous collection state when not changing collection
https://github.com/user-attachments/assets/b83f2668-943e-43a3-b872-e6af5c347d57
=> fix(392): Prevent collapsing Folders when modifying Collection Items

package.json, src/renderer/components/shared/settings/SettingsModal.tsx, src/renderer/components/shared/settings/VariableTab/VariableEditor.tsx, src/renderer/components/ui/checkbox.tsx, src/renderer/components/ui/table.tsx, yarn.lock
- Closes #402
- Increased the width of the Settings Dialog
- Added the Shadcn Checkbox component and added it to the Variables Table
- The Shadcn Checkbox will also be advantageous for future theming support
- Removed the absolute styling in `VariableEditor.tsx`
- Exchanged the SVG Trash Icon with a Lucide Icon since the SVG icon was rendered very small in the button and simple resizing was not working
Tested manually:
https://github.com/user-attachments/assets/4198647c-6366-478c-8349-9a9262ab197f
=> feat(402): Add checkbox to mark and store variables as secrets

src/renderer/components/shared/settings/SettingsModal.tsx, src/renderer/state/collectionStore.ts
- Closes #407 
- Collection variables are now shown correctly after (re-)starting the app.
- Also fixed a bug where, when switching collections, the variables from the previously opened collection were still shown and only updated on the second render of the settings menu. This was resolved by using `useEffect` to update the `editorVariables` state whenever the variables change.
I tested the changes manually. Video:
https://github.com/user-attachments/assets/e7221b51-f2d8-4701-8979-c1779bba6a5b
=> fix(407): Show collection variables correctly after restarting the app

src/renderer/components/mainWindow/MainTopBar.tsx, src/renderer/components/mainWindow/mainTopBar/SendButton.tsx
Added isLoading state in MainTopBar to track request progress.
Updated sendRequest to set isLoading true before sending and false after completion.
Modified SendButton to accept disabled and children props for flexibility.
Show spinner and disable Send button while request is in progress.
Restored arrow icon and re-enabled button after request finishes.
Describe the changes of your PR here
Manually tested clicking Send button: spinner appears, button disables, then resets after response.
Verified error cases reset loading state correctly.
Checked UI remains consistent with no side effects.
=> Add loading indicator to SendButton

src/renderer/components/shared/settings/VariableTab/VariableEditor.tsx, src/renderer/components/ui/secret-input.tsx
This update enhances the SecretInput component by adding a Show/Hide toggle button for password fields.
Default state: password is hidden.
Clicking the toggle switches between masked (password) and visible (text) input types.
=> feat(483 ): Add show/hide Button to Secret Variables

src/main/logging/logger.test.ts, src/main/logging/logger.ts, src/main/network/authentication/oauth2/auth-code-flow.ts, src/main/network/authentication/oauth2/client-credentials.ts, src/main/network/authentication/oauth2/strategy-factory.ts, src/main/network/authentication/oauth2/strategy.ts, src/renderer/components/mainWindow/bodyTabs/InputTabs/tabs/AuthorizationTab/AuthorizationTab.tsx, src/renderer/components/mainWindow/bodyTabs/InputTabs/tabs/AuthorizationTab/ModularForm.tsx, src/renderer/components/shared/settings/VariableTab/VariableEditor.tsx, src/renderer/components/ui/secret-input.tsx, src/shim/logger.ts, src/shim/objects/auth/oauth2.ts
- Implement OAuth2 auth code flow
- Simplify the code for the auth modal
- Support logging secrets which are only shown in console and not stored in the FS logs
- Log OAuth2 requests being made (in console only)
- Fix password input rendering behind the hide/show button
You can test it yourself using https://oauth.tools
https://github.com/user-attachments/assets/ed85621d-4b99-474b-8483-2d609ee86063
=> feat(460): Support Auth Code Flow

src/main/__mocks__/electron/app.ts, src/main/__mocks__/index.ts, src/main/__mocks__/process.ts, src/main/environment/service/environment-service.test.ts, src/main/environment/service/environment-service.ts, src/main/event/main-event-service.ts, src/main/logging/logger.ts, src/main/network/service/http-service.test.ts, src/main/network/service/http-service.ts, src/main/persistence/service/persistence-service.test.ts, src/main/persistence/service/persistence-service.ts, src/renderer/components/shared/settings/SettingsModal.tsx, src/renderer/state/environmentStore.ts, src/renderer/state/variableStore.ts, src/shim/event-service.ts
- Support variables in URL, HTTP header values, and any authorization field
- Fix collection variables not being saved
- Fix secret variables missing after persisting
- Fix global `logger.secret` missing in tests
- Add user agent as automatic header for any request (currently `"User-Agent": "Trufos/0.2.0"`)
- I added automated tests :)
=> feat(413): Variables in URL and HTTP Header Values

docs/architecture/02_rename_behavior.md, src/main/event/main-event-service.ts, src/main/persistence/service/persistence-service.test.ts, src/main/persistence/service/persistence-service.ts, src/renderer/components/sidebar/SidebarRequestList/Nav/Dropdown/modals/NamingModal.tsx, src/renderer/services/event/renderer-event-service.ts, src/renderer/state/collectionStore.ts, src/renderer/state/interface/CollectionStateActions.ts, src/shim/event-service.ts
- Correctly implement rename in backend which also checks for directory name collisions
- Add rename method to event service
- Use new rename method in frontend
- Added automated tests
- Rename a request to the same name as another exitsing. The collision logic worked: `Renaming object at /Users/x/Library/Application Support/Trufos/default-collection/test to /Users/x/Library/Application Support/Trufos/default-collection/echo-2`
=> feat(476): Rename also on FS
